name: Blueprint service
description: Request a new blueprint service
labels: ["request", "blueprint"]
assignees:
  - wschoot
body:
  - type: markdown
    attributes:
      value: |
        The request form below serves the purpose to make requesting a new service in the blueprint easier!
  - type: input
    id: owner
    attributes:
      label: Code owner
      description: Who is the code owner of this service, if it's different from the requestor
      placeholder: ex. Japje
    validations:
      required: false
  - type: textarea
    id: what-is-it
    attributes:
      label: What does the service to?
      description: Tell us, what do you want to host
      placeholder: "Really awesome app for syncing X to Y periodically!"
    validations:
      required: true
  - type: input
    id: hostname
    attributes:
      label: Hostname
      description: Whats the (short) hostname of this server
      placeholder: ex. dnsmaster
    validations:
      required: false
  - type: markdown
    attributes:
      value: ## Resources        
  - type: dropdown
    id: vcpus
    attributes:
      label: vCPU's
      description: Number of virtual CPUs required?
      options:
        - "1"
        - "2"
        - "4"
    validations:
      required: true
  - type: dropdown
    id: memory
    attributes:
      label: RAM
      description: Number of gigabytes RAM required?
      options:
        - "1"
        - "2"
        - "4"
        - "8"
        - "16"
    validations:
      required: true
  - type: dropdown
    id: disk
    attributes:
      label: Disk space
      description: Number of gigabytes Disk space required?
      options:
        - "10"
        - "20"
        - "40"
        - "80"
        - "160"
    validations:
      required: true
  - type: checkboxes
    id: network-external-v4
    attributes:
      label: External IPv4
      description: Do you need an (external) IPv4 address?
      options:
        - label: External IPv4 IP address
          required: false
  - type: checkboxes
    id: network-external-v6
    attributes:
      label: External IPv6
      description: Do you need an (external) IPv6 address?
      options:
        - label: External IPv4 IP address
          required: false
  - type: textarea
    id: extra-internal-ips
    attributes:
      label: Additional internal IPs
      description: Tell us about any additional (internal) IPs you might need
      placeholder: |
        Something like:
        vlan 1234, 1.2.3.4/24
    validations:
      required: false
  - type: textarea
    id: extra-custom-routes
    attributes:
      label: Additional custom routes
      description: Tell us about any additional (custom) routes
      placeholder: |
        Something like:
        10.20.30.40/24 should be routed over interface X or IP Y
    validations:
      required: false
  - type: dropdown
    id: entities
    attributes:
      label: Which entities should the service be available
      multiple: true
      options:
        - NL
        - US
        - Testrack
  - type: textarea
    id: additional-info
    attributes:
      label: What additional info can we use
      description: If you have any additional information that might we relevant, please describe here
  - type: textarea
    id: additional-steps
    attributes:
      label: What additional steps should be performed
      description: We use Ansible to run additional automated steps, if required.
  - type: checkboxes
    id: db-backups
    attributes:
      label: Database backups
      description: If you use a database in this service, please state if they should be backupped regularly using a dump command. This is in addition to nightly backups of the VM itself.
      options:
        - label: Database backups
          required: false
