name: Blueprint service
description: Request a new blueprint service
title: "[BP]: "
labels: ["request", "blueprint"]
assignees:
  - wschoot
body:
  - type: markdown
    attributes:
      value: |
        The request form below serves the purpose to make requesting a new service in the blueprint easier!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: vcpus
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: entities
    attributes:
      label: Which entities should the service be available
      multiple: true
      options:
        - NL
        - US
        - Testrack
  - type: textarea
    id: additional-info
    attributes:
      label: What additional info can we use
      description: If you have any additional information that might we relevant, please describe here
      render: shell
  - type: textarea
    id: additional-steps
    attributes:
      label: What additional steps should be performed
      description: We use Ansible to run additional automated steps, if required.
      render: shell
  - type: checkboxes
    id: db-backups
    attributes:
      label: Database backups
      description: If you use a database in this service, please state if they should be backupped regularly using a dump command. This is in addition to nightly backups of the VM itself.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
